export const INITIAL_TODOS = [
  {
    id: '1',
    title: 'Design landing page hero',
    description: 'Sketch a few directions for the new marketing hero section and share with the team.',
    image_url: null,
    created_at: '2026-07-20T10:00:00Z',
  },
  {
    id: '2',
    title: 'Refactor auth middleware',
    description: 'Clean up the session-check logic and add proper error boundaries for unauthenticated users.',
    image_url: null,
    created_at: '2026-07-21T12:30:00Z',
  },
  {
    id: '3',
    title: 'Write Supabase crash course',
    description: 'Draft the lesson breakdown covering auth, database, storage, and row-level security.',
    image_url: null,
    created_at: '2026-07-22T09:15:00Z',
  },
  {
    id: '4',
    title: 'Fix mobile navigation spacing',
    description: 'Audit the hamburger menu and sidebar panel on small screens; tighten touch targets.',
    image_url: null,
    created_at: '2026-07-22T16:45:00Z',
  },
  {
    id: '5',
    title: 'Dark mode palette review',
    description: 'Verify contrast ratios for all semantic color pairs and document final tokens.',
    image_url: null,
    created_at: '2026-07-23T08:00:00Z',
  },
  {
    id: '6',
    title: 'Set up storage bucket policy',
    description: 'Configure public upload rules for the todo-images bucket and test the upload flow.',
    image_url: null,
    created_at: '2026-07-23T11:20:00Z',
  },
  {
    id: '7',
    title: 'Add loading skeletons',
    description: 'Replace the static placeholders with animated skeleton screens for better perceived performance.',
    image_url: null,
    created_at: '2026-07-23T14:00:00Z',
  },
  {
    id: '8',
    title: 'Write dashboard tests',
    description: 'Cover add, edit, delete, search, and pagination with React Testing Library.',
    image_url: null,
    created_at: '2026-07-23T17:00:00Z',
  },
  {
    id: '9',
    title: 'Prepare demo video',
    description: 'Record a short walkthrough of the login, dashboard, and logout flows for the team.',
    image_url: null,
    created_at: '2026-07-24T09:00:00Z',
  },
];
